### PR TITLE
Use Sidekiq.logger when Sidekiq::Logging is unavailable

### LINKED ISSUE #94: Sidekiq 6.0 does not initialize due to a NameError
### Environment

Using Ruby 2.6, Rails 5.2, I upgraded Sidekiq to the new 6.0 version this morning, which changes how Sidekiq logging is configured.  Upon startup, I received the following error:

/Users/rfine/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rails_semantic_logger-4.4.2/lib/rails_semantic_logger/engine.rb:111:in `block in <class:Engine>': uninitialized constant Sidekiq::Logging (NameError)

The line of code in rails_semantic_logger that is causing this is:

```
      # Replace the Sidekiq logger
      Sidekiq::Logging.logger = SemanticLogger[Sidekiq] if defined?(Sidekiq)
```

The Sidekiq upgrade notes identify the change -- how Sidekiq logging is newly configured in 6.0:

```
Sidekiq.configure_server do |config|
  config.log_formatter = AcmeCorp::PlainLogFormatter.new
  # config.log_formatter = Sidekiq::Logger::Format::JSON.new
end

```

### PR DESCRIPTION
**Pull request by bobvanderlinden**
### Issue # (if available)

Resolves #94

Sidekiq 6.0 has deprecated usage of `Sidekiq::Logger`. `Sidekiq::Logger` is an internal module which applications should not be using. Instead applications should be using `Sidekiq.logger`, as is documented here: https://github.com/mperham/sidekiq/wiki/Logging#api-changes

### Description of changes

This PR attempts to stay backwards compatible by keeping the existing behaviour when `Sidekiq::Logging` still exists and use `Sidekiq.logger` when `Sidekiq::Logging` doesn't exist (which should be the case for Sidekiq 6.0+). 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MisterFine1** [comment]
That build appears to have solved the startup issue -- but I ran into a new one.  When I ran Sidekiq 6.0, during a job, it generated that following error:

NoMethodError: undefined method `with_context' for #<SemanticLogger::Logger:0x00007fa0ec653030>

I'm looking into why now...

**Comment by MisterFine1** [comment]
I opened an issue on sidekiq: https://github.com/mperham/sidekiq/issues/4239

File: lib/rails_semantic_logger/engine.rb [hunk 1]
```diff
@@ -108,7 +108,13 @@ class Engine < ::Rails::Engine
       Resque.logger           = SemanticLogger[Resque] if defined?(Resque) && Resque.respond_to?(:logger)
 
       # Replace the Sidekiq logger
-      Sidekiq::Logging.logger = SemanticLogger[Sidekiq] if defined?(Sidekiq)
+      if defined?(Sidekiq)
+        if defined?(Sidekiq::Logging)
+          Sidekiq::Logging.logger = SemanticLogger[Sidekiq]
+        else
+          Sidekiq.logger = SemanticLogger[Sidekiq]
```
Comment (bobvanderlinden) [inline lib/rails_semantic_logger/engine.rb]: Is this something that would help this PR?

```suggestion
          Sidekiq.logger = SemanticLogger[Sidekiq]
          Sidekiq.logger.extend(Sidekiq::LogContext)
```

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: @bobvanderlinden sorry for the delay. Is there a branch I can use to test this?

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: I tried to patch my rails_semantic_logger with this snippet, but I'm seeing this error

```
sidekiq_1_497f65c0a128 | uninitialized constant Sidekiq::LogContext
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/rails_semantic_logger-4.4.2/lib/rails_semantic_logger/engine.rb:118:in `block in <class:Engine>'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/application/bootstrap.rb:81:in `block in <module:Bootstrap>'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
sidekiq_1_497f65c0a128 | /app/config/environment.rb:5:in `<top (required)>'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/cli.rb:248:in `require'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/cli.rb:248:in `boot_system'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/cli.rb:37:in `run'
sidekiq_1_497f65c0a128 | /usr/local/bundle/gems/sidekiq-6.0.0/bin/sidekiq:12:in `<top (required)>'
sidekiq_1_497f65c0a128 | /usr/local/bundle/bin/sidekiq:23:in `load'
sidekiq_1_497f65c0a128 | /usr/local/bundle/bin/sidekiq:23:in `<top (required)>'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
sidekiq_1_497f65c0a128 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
sidekiq_1_497f65c0a128 | /usr/local/bin/bundle:23:in `load'
sidekiq_1_497f65c0a128 | /usr/local/bin/bundle:23:in `<main>'
```

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: This line instead (taken from [here](https://github.com/mperham/sidekiq/issues/4239#issuecomment-528801658)) seems not to cause issues however, although I have to admit, I'm not entirely sure what either of those lines do

```ruby
Sidekiq.logger.class.alias_method(:with_context, :tagged)
```

Comment (bobvanderlinden) [reply lib/rails_semantic_logger/engine.rb]: Yes. Creating the with_context is a bit dirtier imo, but if Sidekiq::LogContext is indeed not exposed, it is the only way at the moment it seems :(.

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: I think your original PR however works together with sidekiq master though (when 6.0.1 is released). see https://github.com/mperham/sidekiq/issues/4254

So this extra option won't be necessary then, right?

Comment (bobvanderlinden) [reply lib/rails_semantic_logger/engine.rb]: `define_singleton_method` also seems to alter the underlying class. I've made a separate branch that properly implements the `with_context` in a Sidekiq-specific logger class. I think this is the cleanest solution for now, but Sidekiq still overrides `with_context` with the current master version.

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: @bobvanderlinden I'm not sure I follow you precisely. But even if I completely agree and this is a cleaner/nicer/better way, then shouldn't this go into Sidekiq? (where the ugly/dirty/sub-optimal solution lives). At least make a case to change it inside Sidekiq and hopefully other logging libraries would benefit as well?

Ideally Sidekiq plays nicely with any loggers, and the Semantic Logger requires minimal changes to plug-in.

What am I missing?

Comment (bobvanderlinden) [reply lib/rails_semantic_logger/engine.rb]: Sidekiq 'wants' to use a `with_context` function that is in no-way supported by the Rails standard loggers. There is no standard interface for such a function. SemanticLogger has chosen to use `tagged` as the name for such a function; Sidekiq has chosen to use `with_context` as the name. Both do the same thing. Forcing Sidekiq to use `tagged` will not make sense as then Sidekiq is adhering to the interface chosen by `SemanticLogger` (which is likely different for other logging frameworks).

So, Sidekiq always wants to have the ability to enrich its log lines with extra information and does so using the `with_context` function. It forces any logger assigned to Sidekiq to have such a function.

For convenience (and this is where it is in the wrong imo) it creates the `with_context` function to the logger class if it doesn't exist. This is bad.

We can support that quite easily by wrapping our log function with one that aliases `with_context` to `tagged`. We only need to use such a wrapper for Sidekiq specifically and do not need to change any generic SemanticLogger functionality.

It would be nice if Sidekiq didn't use the `with_context` function at all, but I can very well imagine that enriching log lines with extra information is something we'd also want them to do.

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: Thanks for explaining, @bobvanderlinden. Wouldn't it be more fruitful to try to give this feedback to the Sidekiq project? (in case you haven't already, apologies if you have).

Even if we don't agree with what Sidekiq is doing, it is the de-facto standard library for async jobs in rails, and SemanticLogger should play nicely with it right? At least if we want SemanticLoggerRails to support Sidekiq out of the box...

Besides that, the last paragraph confused me a bit... could you clarify what you mean?

> It would be nice if Sidekiq didn't use the with_context function at all, but I can very well imagine that enriching log lines with extra information is something we'd also want them to do.

Comment (bobvanderlinden) [reply lib/rails_semantic_logger/engine.rb]: I have submitted the following issue at Sidekiq: https://github.com/mperham/sidekiq/issues/4296

The last paragraph is about Sidekiq using with_context, which is a function not part of any Rails loggers. Sidekiq using that function means it is relying on non-standard functionality. It would be nice if Sidekiq didn't rely on non-standard functionality, but I can see why they want such a feature: to enrich their logs with extra information.

The issue mentioned might give some more insight as well.

Comment (gingerlime) [reply lib/rails_semantic_logger/engine.rb]: Thanks again, @bobvanderlinden. I missed this sidekiq issue. Looks like it's going forward well and you make a good case there. I'll follow both issues. Let me know if there's anything I can help with. Thanks for doing this!

**Comment by gingerlime** [comment]
I saw that Sidekiq 6.0.1 was released with the changes that @bobvanderlinden proposed. Can we get this PR ready/merged any time soon? :)

**Comment by bobvanderlinden** [comment]
Nice. Yes, the current state of the PR should be working for Sidekiq 6.0.1. It might also be simplified to:

```rb
Sidekiq.logger = SemanticLogger[:Sidekiq] if defined?(Sidekiq)
```

As @mperham mentioned `Sidekiq.logger` is available in Sidekiq for quite some time. It was apparently added back in 2012: https://github.com/mperham/sidekiq/blob/8c9f960a687d234cdee3396117484bc3c92f3219/lib/sidekiq.rb#L94-L96

Shall I just remove all traces of `Sidekiq::Logging.logger` in this PR?

**Comment by gingerlime** [comment]
sounds good to me @bobvanderlinden ! Do you have merge rights on this project though? or I guess we'll have to wait for @reidmorrison, right?

Happy to test this PR when you're ready :) thanks again for your patience and coordinating this whole thing 💯

**Comment by bobvanderlinden** [comment]
Alright, changed the PR to always use `Sidekiq.logger`.

@reidmorrison could you do a review?

**Comment by gingerlime** [comment]
@bobvanderlinden I tested this PR with sidekiq 5.2.7 as well as sidekiq 6.0.1 and it seems to work well 👍 

+1 for integrating context into the logs. I currently use a custom middleware for it, but I think it would be much easier for lots of people if this works out of the box! 👍 🥇

**Comment by gingerlime** [comment]
also, and sorry, I don't want to hijack this thread (maybe I'm also doing something wrong?), but I seem to get a couple of fairly "useless" log entries for sidekiq that I can't fully understand or get rid of...

specifically, I can see an empty "sidekiq start" log, followed by another start with a bit more info (job name, JID)... and same goes for the "sidekiq done" log.

sample initial log entries

```
2019-10-03 10:26:46.553831 INFO name=Sidekiq message=start payload=null tags= named_tags= duration= process_info=153:processor exception=
2019-10-03 10:26:46.564567 INFO name=Sidekiq message=start payload=null tags=[TasksLauncher JID-fe5bd736c7a45019eebac9c4] named_tags= duration= process_info=153:processor exception=
```

... here there are some logs from the worker itself if it logs anything ... 

then at the end

```
2019-10-03 10:26:47.202250 INFO name=Sidekiq message=done: 0.638 sec payload=null tags=[TasksLauncher JID-fe5bd736c7a45019eebac9c4] named_tags= duration= process_info=153:processor exception=
2019-10-03 10:26:47.202440 INFO name=Sidekiq message=done payload=null tags= named_tags= duration= process_info=153:processor exception=
```

Perhaps related to my middleware?

**Comment by bobvanderlinden** [comment]
Maybe that's related to measure and log lines? I'm not sure, but would I consider it a separate issue.

**Comment by gingerlime** [comment]
Yes, you're right. It's definitely unrelated. Hope we can merge this in, and then I can try to play around with this middleware again. Or maybe if the project is ok with it, adding the sidekiq context would remove the need for this middleware entirely.

**Comment by gingerlime** [comment]
@reidmorrison see https://github.com/rocketjob/rails_semantic_logger/pull/95#issuecomment-537836013

> As @mperham mentioned Sidekiq.logger is available in Sidekiq for quite some time. It was apparently added back in 2012: https://github.com/mperham/sidekiq/blob/8c9f960a687d234cdee3396117484bc3c92f3219/lib/sidekiq.rb#L94-L96

I personally tested it with Sidekiq 5.2.7 and 6.0.1 and both worked.

**Comment by bobvanderlinden** [comment]
The first commit of this PR keeps compatibility. See https://github.com/rocketjob/rails_semantic_logger/pull/95/commits/91466a5706d6a97af14ab64577e0f31199166989

The second commit removes compatibility for Sidekiq < 1.2.1. That's for versions more than 7 years old.

The maintainer of Sidekiq (@mperham) suggested to use Sidekiq.logger without relying on the internal logger (Sidekiq::Logger.logger).

Should I add a fallback for using the internal logger again?

**Comment by gingerlime** [comment]
I don't think this project should support backwards compatibility for > 7 years, nor use internal methods, especially if public ones are available and exposed. +1 for merging this as-is.
